# Generated by Django 3.0.6 on 2020-11-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('wrong_price', models.IntegerField(blank=True, null=True)),
                ('correct_price', models.IntegerField(blank=True, null=True)),
                ('delivery_charge', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=60)),
                ('size_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasions.Product')),
            ],
        ),
    ]
