# Generated by Django 3.0.6 on 2020-11-08 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fasions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Products_size',
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('image_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasions.Product')),
            ],
        ),
    ]
