# Generated by Django 3.2.8 on 2022-09-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fasions', '0006_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10)),
                ('streetAdreess', models.CharField(max_length=30)),
                ('apartment', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fasions.customer')),
            ],
        ),
    ]
