# Generated by Django 3.2.8 on 2022-09-13 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fasions', '0011_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
