# Generated by Django 3.2.8 on 2022-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasions', '0012_checkout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='orderName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
