# Generated by Django 3.2.8 on 2022-09-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasions', '0013_auto_20220913_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
