# Generated by Django 3.2.8 on 2022-09-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasions', '0014_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='productName',
        ),
    ]
